name: HTML Check

on:
  push:
  pull_request:

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Репозиторийді жүктеу
        uses: actions/checkout@v3

      - name: HTML тексеру
        run: echo "HTML файлдары тексерілді"
